# Generated by Django 4.2.17 on 2025-11-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره دانشجویی')),
                ('event_type', models.CharField(choices=[('workshop', 'کارگاه رمزنگاری مدرن'), ('ctf', 'مسابقه CTF بهاره'), ('seminar', 'سمینار هوش مصنوعی در امنیت')], max_length=50, verbose_name='نوع رویداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام رویداد',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای رویداد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('role', models.CharField(choices=[('student', 'دانشجو'), ('researcher', 'پژوهشگر'), ('faculty', 'عضو هیئت علمی')], max_length=50, verbose_name='نقش')),
                ('interest', models.TextField(blank=True, null=True, verbose_name='زمینه علاقه\u200cمندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'عضویت',
                'verbose_name_plural': 'عضویت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
