# Generated by Django 4.2.17 on 2025-11-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان رویداد')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_at', models.DateTimeField(verbose_name='زمان برگزاری')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل برگزاری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/قابل نمایش')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['-start_at'],
            },
        ),
    ]
