# Generated by Django 4.2.17 on 2025-11-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date', '-created_at'], 'verbose_name': 'رویداد/دوره', 'verbose_name_plural': 'رویدادها و دوره\u200cها'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='event_type',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان رویداد'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'کارگاه'), ('course', 'دوره'), ('seminar', 'سمینار'), ('ctf', 'مسابقه CTF'), ('conference', 'همایش'), ('other', 'سایر')], default='other', max_length=50, verbose_name='نوع رویداد'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='تصویر رویداد'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='منتشر شده'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=True, verbose_name='ثبت\u200cنام باز است'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event', verbose_name='رویداد'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مکان برگزاری'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان رویداد/دوره'),
        ),
    ]
