# Generated by Django 4.2.17 on 2025-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_options_remove_event_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح تصویر')),
                ('image', models.ImageField(upload_to='images/gallery/', verbose_name='فایل تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزوده\u200cشدن')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
